imports:
    - { resource: parameters.yml }
    - { resource: services.yml }
    - { resource: "@AppBundle/Resources/config/services.yml" }

parameters:
    locale: en

# framework Configuration
framework:
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
